package transactions;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ask
 */
import databaseConnections.QueryExecution;
import java.util.Calendar;
import javax.swing.JOptionPane;
import exceptions.ExceptionThrower;
import exceptions.LetterFoundException;
import exceptions.NullFieldException;
import static utilities.Utilities.resetEnabled;
import static utilities.Utilities.resetFields;

public class Advance extends javax.swing.JFrame {

    /**
     * Creates new form Advance
     */
    
    private final QueryExecution advanceQuery;
    
    public Advance() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        
        advanceQuery = new QueryExecution();
        
        employeePanel.setVisible(false);
        resetEnabled( false, issueDate,maxAmount,yourAmount,apply,nameField,
                            contactNumberField,reset,aadhaarCardNo,dobField );
        
        Calendar today = Calendar.getInstance();
        issueDate.setDate(today.getTime());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        employeeID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        issueDate = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        maxAmount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        yourAmount = new javax.swing.JTextField();
        employeePanel = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        contactNumberField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dobField = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        aadhaarCardNo = new javax.swing.JTextField();
        enter = new javax.swing.JButton();
        apply = new javax.swing.JButton();
        reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Advance Payment");

        jLabel1.setText("EmployeeID");

        jLabel2.setText("Date");

        jLabel3.setText("Max Amount Allowed");

        jLabel4.setText("Advance You Want");

        imageLabel.setText("jLabel5");

        jLabel6.setText("Name");

        jLabel7.setText("Contact Number");

        jLabel5.setText("Date Of Birth");

        jLabel8.setText("Aadhaar Card No");

        javax.swing.GroupLayout employeePanelLayout = new javax.swing.GroupLayout(employeePanel);
        employeePanel.setLayout(employeePanelLayout);
        employeePanelLayout.setHorizontalGroup(
            employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addGap(48, 48, 48)
                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameField)
                    .addComponent(contactNumberField, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(dobField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aadhaarCardNo))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        employeePanelLayout.setVerticalGroup(
            employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePanelLayout.createSequentialGroup()
                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(employeePanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(employeePanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(contactNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(dobField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(aadhaarCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        enter.setText("Enter");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });

        apply.setText("Apply");
        apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyActionPerformed(evt);
            }
        });

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(employeeID)
                    .addComponent(issueDate, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(maxAmount)
                    .addComponent(yourAmount)
                    .addComponent(apply)
                    .addComponent(reset))
                .addGap(39, 39, 39)
                .addComponent(enter)
                .addGap(27, 27, 27)
                .addComponent(employeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(employeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enter))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(issueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(maxAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(yourAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(apply)
                        .addGap(18, 18, 18)
                        .addComponent(reset))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(employeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(247, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        
        if(employeeID.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Enter EmployeeID");
        }else{
            
            advanceQuery.setParameters("CheckingAdvanceTakenOrNot", employeeID);
            advanceQuery.getResult(maxAmount,nameField,contactNumberField,dobField,aadhaarCardNo,imageLabel);
            
            int returnedValue = advanceQuery.getReturnedValue();
            if( returnedValue == 2 ){
                employeePanel.setVisible(true);
                employeeID.setEnabled(false);
                resetEnabled(true, yourAmount,apply,reset);
                
            }else if( returnedValue == 0 ){
                JOptionPane.showMessageDialog(this, "Wrong EmployeeID");
            }else if( returnedValue == 1 ){
                JOptionPane.showMessageDialog(this, "You have Already taken Advance money this month");
            }else if(returnedValue == 3){
                JOptionPane.showMessageDialog(this, "This Employee Had Left The Job");
            }
        }
    }//GEN-LAST:event_enterActionPerformed

    private void applyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyActionPerformed
        
        try {
            ExceptionThrower.nullFields(yourAmount);
            ExceptionThrower.letterFound(true, yourAmount);
            
            double amountEntered = Double.parseDouble(yourAmount.getText());
            double maxAmountAllowed = Double.parseDouble(maxAmount.getText());
            if(amountEntered > maxAmountAllowed){
                JOptionPane.showMessageDialog(this, "Not Allowed");
            }else{
                advanceQuery.setParameters("AdvanceApplied", employeeID,yourAmount);
                advanceQuery.getResult();
                
                //------Returned Value not Required as it will lways return 1
                JOptionPane.showMessageDialog(this, "Advance Issued to "+employeeID.getText());
                
                employeeID.setEnabled(true);
                apply.setEnabled(false);
                yourAmount.setEnabled(false);
                employeePanel.setVisible(false);
                resetFields(employeeID,maxAmount,yourAmount);    
            }
        } catch (NullFieldException e) {
            JOptionPane.showMessageDialog(this, "Enter Amount");
        }catch(LetterFoundException e) {
            JOptionPane.showMessageDialog(this, "Enter Valid Amount");
        }
            
        
    }//GEN-LAST:event_applyActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        
        resetFields(employeeID,maxAmount,yourAmount);
        resetEnabled(false, apply,yourAmount,reset);
        employeeID.setEnabled(true);
        employeePanel.setVisible(false);
        
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Advance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Advance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Advance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Advance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Advance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aadhaarCardNo;
    private javax.swing.JButton apply;
    private javax.swing.JTextField contactNumberField;
    private com.toedter.calendar.JDateChooser dobField;
    private javax.swing.JTextField employeeID;
    private javax.swing.JPanel employeePanel;
    private javax.swing.JButton enter;
    private javax.swing.JLabel imageLabel;
    private com.toedter.calendar.JDateChooser issueDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField maxAmount;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton reset;
    private javax.swing.JTextField yourAmount;
    // End of variables declaration//GEN-END:variables
}
