/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package master;

/**
 *
 * @author ask
 */
import databaseConnections.Departments;
import databaseConnections.QueryExecution;
import images.YourImage;
import javax.swing.JOptionPane;
import exceptions.NullFieldException;
import static utilities.Utilities.resetEnabled;
import static utilities.Utilities.turnVisible;

public class DepartmentMaster extends javax.swing.JFrame {

    /**
     * Creates new form DepartmentMaster
     */
    private final QueryExecution query;
    
    public DepartmentMaster() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        
        query = new QueryExecution();   //Query Executing Object
        
        deptCombo.addItem("");
        Departments.setDepartments(deptCombo);
        turnVisible(false, InfoPanel,update,remove);
        resetEnabled(false, hNameField,hIDField,noOfEmployeesField);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        urGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dNameField = new javax.swing.JTextField();
        idField = new javax.swing.JTextField();
        deptCombo = new javax.swing.JComboBox<>();
        submit = new javax.swing.JButton();
        InfoPanel = new javax.swing.JPanel();
        hImageLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        hIDField = new javax.swing.JTextField();
        hNameField = new javax.swing.JTextField();
        noOfEmployeesField = new javax.swing.JTextField();
        update = new javax.swing.JRadioButton();
        remove = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Departments");

        jLabel1.setText("Department Name");

        jLabel2.setText("HeadID");

        jLabel3.setText("Departments In Company");

        deptCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                deptComboItemStateChanged(evt);
            }
        });

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        hImageLabel.setText("jLabel4");

        jLabel6.setText("HeadID");

        jLabel7.setText("Head Name");

        jLabel8.setText("No Of Employees in this Department");

        javax.swing.GroupLayout InfoPanelLayout = new javax.swing.GroupLayout(InfoPanel);
        InfoPanel.setLayout(InfoPanelLayout);
        InfoPanelLayout.setHorizontalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(hImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hIDField, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(hNameField)
                    .addComponent(noOfEmployeesField))
                .addGap(32, 32, 32))
        );
        InfoPanelLayout.setVerticalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPanelLayout.createSequentialGroup()
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InfoPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(hImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InfoPanelLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(InfoPanelLayout.createSequentialGroup()
                                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(hIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addComponent(jLabel7))
                            .addComponent(hNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(noOfEmployeesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        update.setText("Update");
        update.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                updateItemStateChanged(evt);
            }
        });

        remove.setText("Remove");
        remove.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                removeItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(submit)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(update)
                            .addComponent(remove)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(deptCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, 189, Short.MAX_VALUE)
                        .addComponent(idField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dNameField, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addComponent(InfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(dNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(deptCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(update))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(submit)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(remove)))
                .addContainerGap(193, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        
        try{
            if(dNameField.getText().equals(""))
                throw new NullFieldException("department name not entered");
            
            int yourOption = JOptionPane.showConfirmDialog(this, "Are you Sure ?");
            if(yourOption == JOptionPane.YES_OPTION && !update.isSelected()&& !remove.isSelected()){
                query.setParameters("AddingNewDepartment", dNameField,idField);
                query.getResult();
                int returnedValue = query.getReturnedValue();
                if( returnedValue == 1 || returnedValue == 2 || returnedValue == 5 || returnedValue == 4 ){
                    JOptionPane.showMessageDialog(this, "Saved Successfully");
                    deptCombo.addItem(dNameField.getText());
                    deptCombo.setSelectedIndex(0);
                }else if ( returnedValue == 3 ){
                    JOptionPane.showMessageDialog(this, "Wrong HeadID");
                }else if ( returnedValue == 0 ){
                    JOptionPane.showMessageDialog(this, "Allready Exists");
                }else if ( returnedValue == 6 ){
                    JOptionPane.showMessageDialog(this, "Employee with this ID has left the job");
                }
            }else if( yourOption == JOptionPane.YES_OPTION && update.isSelected() ){
                
                query.setParameters( "UpdateDepartment", dNameField,idField );
                query.getResult();
                
                int returnedValue = query.getReturnedValue();
                if( returnedValue == 1 || returnedValue == 2 ){
                    
                    JOptionPane.showMessageDialog(this, "Updated Successfully");
                    deptCombo.setSelectedIndex(0);
                    deptCombo.setEnabled(true);
                    
                }else if ( returnedValue == 0 ){
                    JOptionPane.showMessageDialog(this, "Wrong HeadID");
                }else if( returnedValue == 3 ){
                    JOptionPane.showMessageDialog(this, "This Employee Had Left Job");
                }
                
            }else if( yourOption == JOptionPane.YES_OPTION && remove.isSelected()){
                query.setParameters("RemovingDepartment", dNameField);
                query.getResult();
                int returnedValue = query.getReturnedValue();
                
                if( returnedValue == 1 ){
                    JOptionPane.showMessageDialog(this, "Removed Successfully");
                    deptCombo.setSelectedIndex(0);
                    deptCombo.setEnabled(true);
                }
            }
        }catch(NullFieldException e){
            JOptionPane.showMessageDialog(this, "Enter Department Name");
        }
    }//GEN-LAST:event_submitActionPerformed

    private void deptComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_deptComboItemStateChanged
        
        if(!deptCombo.getSelectedItem().toString().equals("")){
            
            turnVisible(true, InfoPanel,update,remove);
            resetEnabled(false, dNameField,idField);
            
            query.setParameters("SearchingDepartment", deptCombo);
            query.getResult(hIDField,hNameField,noOfEmployeesField,hImageLabel);
            
            int returnedValue = query.getReturnedValue();
            if( returnedValue == 1 ){
                new YourImage().setImage(hImageLabel, true);
            }
            
            dNameField.setText(deptCombo.getSelectedItem().toString());
            idField.setText(hIDField.getText());
            
        } else {
            turnVisible(false, InfoPanel,update,remove);
            resetEnabled(true, dNameField,idField);
            update.setSelected(false);
            remove.setSelected(false);
            dNameField.setText("");
            idField.setText("");
        }
    }//GEN-LAST:event_deptComboItemStateChanged

    private void updateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_updateItemStateChanged
        
        if(update.isSelected()){
            remove.setSelected(false);
            resetEnabled(true, dNameField,idField);
            deptCombo.setEnabled(false);
        }else{
            resetEnabled(false, dNameField,idField);
            deptCombo.setEnabled(true);
        }
    }//GEN-LAST:event_updateItemStateChanged

    private void removeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_removeItemStateChanged
        
        if(remove.isSelected()){
            update.setSelected(false);
            deptCombo.setEnabled(false);
        }else{
            deptCombo.setEnabled(true);
        }
    }//GEN-LAST:event_removeItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepartmentMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepartmentMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepartmentMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepartmentMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepartmentMaster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InfoPanel;
    private javax.swing.JTextField dNameField;
    private javax.swing.JComboBox<String> deptCombo;
    private javax.swing.JTextField hIDField;
    private javax.swing.JLabel hImageLabel;
    private javax.swing.JTextField hNameField;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField noOfEmployeesField;
    private javax.swing.JRadioButton remove;
    private javax.swing.JButton submit;
    private javax.swing.JRadioButton update;
    private javax.swing.ButtonGroup urGroup;
    // End of variables declaration//GEN-END:variables
}
