package transactions;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ask
 */
import databaseConnections.QueryExecution;
import images.YourImage;
import java.util.Calendar;
import javax.swing.JOptionPane;
import static utilities.Utilities.resetEnabled;
import static utilities.Utilities.resetFields;

public class MonthlyPayments extends javax.swing.JFrame {

    /**
     * Creates new form MonthlyPayments
     */
    final double MONEY_DEDUCTION_PER_LEAVE = 10.50;
    final double PERFORMANCE_MONEY = 100;
    final int MAX_ALLOWED_LEAVES = 3;
    
    private final QueryExecution salaryQuery;
    
    public MonthlyPayments() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        salaryQuery = new QueryExecution();
        resetEnabled(false, payDate,scaleAmmount,leaveDeduction,performanceIncentives,advanceDeduction,
                        nameField,contactField,dobField,performance,noOfLeaves,salaryPaid,pay,reset);
        Calendar today = Calendar.getInstance();
        payDate.setDate(today.getTime());
        new YourImage().setImage(employeeImage, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        employeeIDField = new javax.swing.JTextField();
        payDate = new com.toedter.calendar.JDateChooser();
        scaleAmmount = new javax.swing.JTextField();
        leaveDeduction = new javax.swing.JTextField();
        advanceDeduction = new javax.swing.JTextField();
        performanceIncentives = new javax.swing.JTextField();
        salaryPaid = new javax.swing.JTextField();
        pay = new javax.swing.JButton();
        employeePanel = new javax.swing.JPanel();
        employeeImage = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        dobField = new com.toedter.calendar.JDateChooser();
        contactField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        noOfLeaves = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        performance = new javax.swing.JTextField();
        check = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Monthly Payment");

        jLabel1.setText("EmployeeID");

        jLabel2.setText("Pay Date");

        jLabel4.setText("Scale Ammount");

        jLabel6.setText("Leave Deduction");

        jLabel7.setText("Advance Deduction");

        jLabel8.setText("Performance Incentives");

        jLabel9.setText("Salary Paid");

        pay.setText("Pay");
        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });

        employeeImage.setText("jLabel10");

        jLabel11.setText("Name");

        jLabel12.setText("Date Of Birth");

        jLabel13.setText("Contact Number");

        jLabel3.setText("No Of Leaves");

        jLabel5.setText("Performance");

        javax.swing.GroupLayout employeePanelLayout = new javax.swing.GroupLayout(employeePanel);
        employeePanel.setLayout(employeePanelLayout);
        employeePanelLayout.setHorizontalGroup(
            employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(employeeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(39, 39, 39)
                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noOfLeaves)
                    .addComponent(performance)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dobField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contactField))
                .addGap(74, 74, 74))
        );
        employeePanelLayout.setVerticalGroup(
            employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePanelLayout.createSequentialGroup()
                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(employeePanelLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(dobField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(contactField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(noOfLeaves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(performance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(employeePanelLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(employeeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        check.setText("Check");
        check.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkItemStateChanged(evt);
            }
        });

        jLabel10.setText("Note* : 3 Leaves are allowed");

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9))
                                .addGap(87, 87, 87)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(leaveDeduction)
                                    .addComponent(advanceDeduction)
                                    .addComponent(performanceIncentives)
                                    .addComponent(salaryPaid)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                                .addComponent(scaleAmmount, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(201, 201, 201)
                                .addComponent(pay)
                                .addGap(41, 41, 41)
                                .addComponent(reset))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(87, 87, 87)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(employeeIDField)
                                    .addComponent(payDate, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addComponent(check))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(employeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(222, 222, 222))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel4, jLabel6, jLabel7, jLabel8, jLabel9});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(check)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(employeeIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(payDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(scaleAmmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(leaveDeduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(advanceDeduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(performanceIncentives, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(salaryPaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pay)
                            .addComponent(reset))
                        .addGap(17, 17, 17)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(employeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {advanceDeduction, employeeIDField, jLabel1, jLabel2, jLabel4, jLabel6, jLabel7, jLabel8, jLabel9, leaveDeduction, payDate, performanceIncentives, salaryPaid, scaleAmmount});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkItemStateChanged
        
        if(check.isSelected()){
            if(employeeIDField.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Enter EmployeeID");
            }else{
                
                salaryQuery.setParameters("SalaryChecking", employeeIDField);
                salaryQuery.getResult(nameField,dobField,contactField,scaleAmmount,noOfLeaves,performance,advanceDeduction,employeeImage);
                int returnedValue = salaryQuery.getReturnedValue();
                if(returnedValue == 0){
                    JOptionPane.showMessageDialog(this, "Wrong EmployeeID");
                }else if (returnedValue == 2){
                    JOptionPane.showMessageDialog(this, "This Employee Had Already Left the Job");
                }else if(returnedValue == 3){
                    JOptionPane.showMessageDialog(this, "Can't Pay Because Days in Company Less Than 30");
                }else if (returnedValue == 4){
                    JOptionPane.showMessageDialog(this, "Already Taken Salary THis Month");
                }else if (returnedValue == 1){
                    pay.setEnabled(true);
                    reset.setEnabled(true);
                    employeeIDField.setEnabled(false);
                    check.setEnabled(false);
                    double leaveAmount = 0;
                    int leaveTaken=Integer.parseInt(noOfLeaves.getText());
                    if(leaveTaken>MAX_ALLOWED_LEAVES){
                        leaveAmount=(leaveTaken-MAX_ALLOWED_LEAVES)*MONEY_DEDUCTION_PER_LEAVE;
                        leaveDeduction.setText((leaveAmount)+"");
                    }else{
                        leaveDeduction.setText(leaveAmount+"");
                    }
                    double performanceAmount = Integer.parseInt(performance.getText())*PERFORMANCE_MONEY;
                    performanceIncentives.setText(performanceAmount+"");
                    
                    double advancetaken = Double.parseDouble(advanceDeduction.getText());
                    
                    double scaleAmountRecieved = Double.parseDouble(scaleAmmount.getText());
                    double salaryToBedPaid=scaleAmountRecieved-leaveAmount-advancetaken+performanceAmount;
                    
                    salaryPaid.setText(salaryToBedPaid+"");
                }
            }
        }
        
    }//GEN-LAST:event_checkItemStateChanged

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
        
        salaryQuery.setParameters("PaySalary", employeeIDField,payDate,scaleAmmount,
                            leaveDeduction,advanceDeduction, performanceIncentives,salaryPaid);
        
        salaryQuery.getResult();
        
        //-----------Not Required Returned Value As it will return 1 always 
        resetFields(employeeIDField,scaleAmmount,leaveDeduction,advanceDeduction,performanceIncentives,salaryPaid
                    ,nameField,dobField,contactField,noOfLeaves,performance,check);
        new YourImage().setImage(employeeImage, true);
        pay.setEnabled(false);
        reset.setEnabled(false);
        check.setSelected(false);
        check.setEnabled(true);
        employeeIDField.setEnabled(true);
    }//GEN-LAST:event_payActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        
        employeeIDField.setEnabled(true);
        resetFields(advanceDeduction,scaleAmmount,leaveDeduction,nameField,contactField,
                    dobField,noOfLeaves,performance,salaryPaid,performanceIncentives);
        new YourImage().setImage(employeeImage, true);
       pay.setEnabled(false);
        reset.setEnabled(false);
        check.setSelected(false);
        check.setEnabled(true);
        
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonthlyPayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonthlyPayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonthlyPayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonthlyPayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonthlyPayments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField advanceDeduction;
    private javax.swing.JRadioButton check;
    private javax.swing.JTextField contactField;
    private com.toedter.calendar.JDateChooser dobField;
    private javax.swing.JTextField employeeIDField;
    private javax.swing.JLabel employeeImage;
    private javax.swing.JPanel employeePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField leaveDeduction;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField noOfLeaves;
    private javax.swing.JButton pay;
    private com.toedter.calendar.JDateChooser payDate;
    private javax.swing.JTextField performance;
    private javax.swing.JTextField performanceIncentives;
    private javax.swing.JButton reset;
    private javax.swing.JTextField salaryPaid;
    private javax.swing.JTextField scaleAmmount;
    // End of variables declaration//GEN-END:variables
}
