/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package master;

import databaseConnections.Designation;
import databaseConnections.QueryExecution;
import javax.swing.JOptionPane;
import exceptions.ExceptionThrower;
import exceptions.LetterFoundException;
import exceptions.NullFieldException;

/**
 *
 * @author ask
 */
import static utilities.Utilities.resetEnabled;
import static utilities.Utilities.resetFields;

public class SalaryScaleMaster extends javax.swing.JFrame {

    /**
     * Creates new form SalaryScaleMaster
     */
    private final QueryExecution salQuery;
    
    public SalaryScaleMaster() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        
        salQuery = new QueryExecution();
        designationCombo.addItem("");
        Designation.setDesignation(designationCombo);
        resetEnabled(false, hraField,baseAmountField,totalAmountField,
                        taField,daField,taxField,pfField,submit,save);
        updateRadio.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        designationCombo = new javax.swing.JComboBox<>();
        baseAmountField = new javax.swing.JTextField();
        hraField = new javax.swing.JTextField();
        taField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        daField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        taxField = new javax.swing.JTextField();
        pfField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        totalAmountField = new javax.swing.JTextField();
        save = new javax.swing.JRadioButton();
        updateRadio = new javax.swing.JRadioButton();
        submit = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Salary Scale");

        jLabel3.setText("Base Amount");

        designationCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                designationComboItemStateChanged(evt);
            }
        });

        jLabel5.setText("TA");

        jLabel4.setText("HRA");

        jLabel6.setText("DA");

        jLabel7.setText("Tax");

        jLabel8.setText("PF");

        jLabel2.setText("Total Amount");

        save.setText("Save");
        save.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                saveItemStateChanged(evt);
            }
        });

        updateRadio.setText("Update Existsing");
        updateRadio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                updateRadioItemStateChanged(evt);
            }
        });

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jLabel9.setText("Designation");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(155, 155, 155))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(154, 154, 154))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(taxField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(daField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hraField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(baseAmountField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(designationCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pfField)
                    .addComponent(totalAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(submit)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(save)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updateRadio)))))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(designationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(baseAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(hraField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(taField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(daField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(taxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(pfField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(totalAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateRadio)
                    .addComponent(save))
                .addGap(18, 18, 18)
                .addComponent(submit)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void designationComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_designationComboItemStateChanged
        
        if(!designationCombo.getSelectedItem().toString().equals("")){
            
            salQuery.setParameters("SearchSalaryScale", designationCombo);
            salQuery.getResult(baseAmountField,hraField,taField,daField,taxField,pfField,totalAmountField);
            int returnedValue = salQuery.getReturnedValue();
            if( returnedValue == 1 ){
                updateRadio.setVisible(true);
                resetEnabled(false, hraField,baseAmountField,taField,daField,taxField,pfField,save);
            }else{
                updateRadio.setVisible(false);
                resetFields(baseAmountField,hraField,taField,daField,taxField,pfField,totalAmountField);
                resetEnabled(true, hraField,baseAmountField,taField,daField,taxField,pfField,save);
            }   
        }else{
            resetFields(baseAmountField,hraField,taField,daField,taxField,pfField,totalAmountField);
            resetEnabled(false, hraField,baseAmountField,taField,daField,taxField,pfField,save);
            updateRadio.setVisible(false);
        }
        save.setSelected(false);
        
    }//GEN-LAST:event_designationComboItemStateChanged

    private void updateRadioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_updateRadioItemStateChanged
        
        if(updateRadio.isSelected()){
            resetEnabled(true, hraField,baseAmountField,taField,daField,taxField,pfField,save);
            designationCombo.setEnabled(false);
        }else{
            resetEnabled(false, hraField,baseAmountField,taField,daField,taxField,pfField);
            save.setEnabled(false);
            save.setSelected(false);
            designationCombo.setEnabled(true);
        }
        
    }//GEN-LAST:event_updateRadioItemStateChanged

    private void saveItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_saveItemStateChanged
        
        if(save.isSelected()){
            double totalAmount = Double.parseDouble(baseAmountField.getText())
                                -Double.parseDouble(hraField.getText())
                                -Double.parseDouble(taField.getText())
                                -Double.parseDouble(daField.getText())
                                -Double.parseDouble(taxField.getText())
                                -Double.parseDouble(pfField.getText());
            
            totalAmountField.setText(totalAmount+"");
            submit.setEnabled(true);
            resetEnabled(false, hraField,baseAmountField,taField,daField,taxField,pfField);
            
        }else{
            totalAmountField.setText("");
            submit.setEnabled(false);
        }
    }//GEN-LAST:event_saveItemStateChanged

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        
        try {
            ExceptionThrower.nullFields(baseAmountField,hraField,taField,daField,taxField,pfField);
            ExceptionThrower.letterFound(true, baseAmountField,hraField,taField,daField,
                                                taxField,pfField,totalAmountField);
            
            if(updateRadio.isSelected()){
                int yourOption = JOptionPane.showConfirmDialog(this, "Sure to update", "Update", JOptionPane.YES_NO_OPTION);
                if(yourOption == JOptionPane.YES_OPTION){
                    
                    salQuery.setParameters("UpdateSalaryScale", designationCombo,baseAmountField,
                            hraField,taField,daField,taxField,pfField,totalAmountField);
                    salQuery.getResult();
                    
                    //--------------Not required returned Value Because it will Always Return 1-----
                    JOptionPane.showMessageDialog(this, "Updates Successfully!", "Done.", JOptionPane.NO_OPTION);
                    
                    designationCombo.setSelectedIndex(0);
                    updateRadio.setSelected(false);
                    
                }
            }else{
                int yourOption = JOptionPane.showConfirmDialog(this, "Sure to submit", "Submit", JOptionPane.YES_NO_OPTION);
                if(yourOption == JOptionPane.YES_OPTION){
                    salQuery.setParameters("AddSalaryScale", designationCombo,baseAmountField,
                            hraField,taField,daField,taxField,pfField,totalAmountField);
                    salQuery.getResult();
                    
                    //--------------Not required returned Value Because it will Always Return 1-----
                    JOptionPane.showMessageDialog(this, "Saved Successfully!", "Done.", JOptionPane.NO_OPTION);
                    
                    designationCombo.setSelectedIndex(0);
                    
                }
            }
        } catch (NullFieldException e) {
            JOptionPane.showMessageDialog(this, "No Field Can be Left Empty");
        }catch (LetterFoundException e){
            JOptionPane.showMessageDialog(this, "No Letters Allowed");
        }
        
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalaryScaleMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalaryScaleMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalaryScaleMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalaryScaleMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalaryScaleMaster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField baseAmountField;
    private javax.swing.JTextField daField;
    private javax.swing.JComboBox<String> designationCombo;
    private javax.swing.JTextField hraField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField pfField;
    private javax.swing.JRadioButton save;
    private javax.swing.JButton submit;
    private javax.swing.JTextField taField;
    private javax.swing.JTextField taxField;
    private javax.swing.JTextField totalAmountField;
    private javax.swing.JRadioButton updateRadio;
    // End of variables declaration//GEN-END:variables
}
