/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Employee;

import databaseConnections.Departments;
import databaseConnections.Designation;
import databaseConnections.QueryExecution;
import images.YourImage;
import java.io.File;
import javax.swing.JOptionPane;
import exceptions.ExceptionThrower;
import exceptions.InvalidDateFoundException;
import exceptions.LetterFoundException;
import exceptions.NullFieldException;
import exceptions.RequiredLegthNotFoundException;
import exceptions.SymbolFoundException;
import exceptions.TooOldException;
import exceptions.TooYoungException;
import static utilities.Utilities.resetEnabled;
import reports.ReportBase;
/**
 *
 * @author ask
 */
public class SearchAndUpdate extends javax.swing.JFrame {

    /**
     * Creates new form SearchAndUpdate
     */
    private File selectedFilePath;
    private final int MAX_LENGTH_CONTACT = 10;
    private final int MAX_LENGTH_AADHAAR = 12;
    private String deptCode, desigCode, yourID;
    private String deptString, desigString, yourString, numberString;
    
    private final QueryExecution query;
    
    public SearchAndUpdate() {
        initComponents();
        employeeID.setEnabled(false);
        employeeName.setEnabled(false);
        setExtendedState(MAXIMIZED_BOTH);
        
        query = new QueryExecution();
        ReportBase.setTable(this, 30, 125, 1300, 500);
        
        Departments.setDepartments(departmentCombo);
        Designation.setDesignation(designationCombo);
        Designation.setDesignation(searchDesignationCombo);
        Departments.setDepartments(searchDepartmentCombo);
        
        searchPanel1.setVisible(false);
        
        resetEnabled( false, empID, nameField, fatherField, motherField, marriedCombo, genderField,
                        dobField, dojField, dojlField, nationalityField, contactField, aadhaarCardField,
                        addressArea, cityCombo, stateCombo, designationCombo, departmentCombo,
                        qualificationArea, performanceField, employeeImageLabel, emailField, update );
        
        employeeID.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yourChoice = new javax.swing.ButtonGroup();
        usingEmployeeID = new javax.swing.JRadioButton();
        usingEmployeeName = new javax.swing.JRadioButton();
        employeeID = new javax.swing.JTextField();
        employeeName = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        searchPanel1 = new javax.swing.JPanel();
        employeeImageLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        fatherField = new javax.swing.JTextField();
        motherField = new javax.swing.JTextField();
        contactField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        genderField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nationalityField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        marriedCombo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressArea = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        cityCombo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        stateCombo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        aadhaarCardField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        departmentCombo = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        designationCombo = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        qualificationArea = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        dojlField = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        performanceField = new javax.swing.JTextField();
        dojField = new com.toedter.calendar.JDateChooser();
        dobField = new com.toedter.calendar.JDateChooser();
        updateRadio = new javax.swing.JRadioButton();
        update = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        empID = new javax.swing.JTextField();
        searchDepartmentCombo = new javax.swing.JComboBox<>();
        searchDesignationCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search And Update Employee Data");

        yourChoice.add(usingEmployeeID);
        usingEmployeeID.setText("Using EmployeeID");
        usingEmployeeID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                usingEmployeeIDItemStateChanged(evt);
            }
        });

        yourChoice.add(usingEmployeeName);
        usingEmployeeName.setText("Using Employee Name");
        usingEmployeeName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                usingEmployeeNameItemStateChanged(evt);
            }
        });

        employeeID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                employeeIDKeyTyped(evt);
            }
        });

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        employeeImageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeImageLabelMouseClicked(evt);
            }
        });

        jLabel1.setText("Name");

        jLabel2.setText("Father Name");

        jLabel3.setText("Mother Name");

        jLabel4.setText("Date Of Birth");

        jLabel5.setText("Contact Number");

        jLabel6.setText("Gender");

        jLabel7.setText("Nationality");

        jLabel8.setText("Maried Status");

        marriedCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married", "Divorced", "Widow" }));

        jLabel9.setText("Address");

        addressArea.setColumns(20);
        addressArea.setRows(5);
        jScrollPane1.setViewportView(addressArea);

        jLabel10.setText("City");

        cityCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Karnal", "Hisar", "Gurgaon", "Rohtak", "Ambala", "Sirsa", "Panipat", "Yamuna Nagar", "Kaithal", "Chandigarh", "Kurukshetra", "Bhiwani", "Faridabad", "Jhajjar", "Bahadurgarh", "Jind", "Rewari", "Sonipat", "Fatehbad", "Nilokheri", "Panchkula" }));

        jLabel11.setText("State");

        stateCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Haryana" }));

        jLabel12.setText("Aadhaar Card No");

        jLabel13.setText("Email");

        jLabel14.setText("Department");

        departmentCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                departmentComboItemStateChanged(evt);
            }
        });

        jLabel15.setText("Designation");

        designationCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                designationComboItemStateChanged(evt);
            }
        });

        jLabel16.setText("Qualification");

        qualificationArea.setColumns(20);
        qualificationArea.setRows(5);
        jScrollPane2.setViewportView(qualificationArea);

        jLabel17.setText("Date Of Joining");

        jLabel18.setText("Date Of Job Left");

        jLabel19.setText("Performance");

        updateRadio.setText("Update");
        updateRadio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                updateRadioItemStateChanged(evt);
            }
        });

        update.setText("Submit");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jLabel20.setText("EmployeeID");

        javax.swing.GroupLayout searchPanel1Layout = new javax.swing.GroupLayout(searchPanel1);
        searchPanel1.setLayout(searchPanel1Layout);
        searchPanel1Layout.setHorizontalGroup(
            searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanel1Layout.createSequentialGroup()
                .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(employeeImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(searchPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(searchPanel1Layout.createSequentialGroup()
                                .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel20))
                                .addGap(57, 57, 57)
                                .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameField)
                                    .addComponent(fatherField)
                                    .addComponent(motherField)
                                    .addComponent(dobField, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                    .addComponent(empID)))
                            .addGroup(searchPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(43, 43, 43)
                                .addComponent(contactField)))))
                .addGap(166, 166, 166)
                .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(34, 34, 34)
                .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(genderField)
                    .addComponent(nationalityField)
                    .addComponent(marriedCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addComponent(cityCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stateCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aadhaarCardField)
                    .addComponent(emailField))
                .addGap(139, 139, 139)
                .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(updateRadio))
                .addGap(72, 72, 72)
                .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(dojField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(performanceField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                        .addComponent(designationCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(departmentCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dojlField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchPanel1Layout.setVerticalGroup(
            searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanel1Layout.createSequentialGroup()
                        .addComponent(employeeImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(empID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(fatherField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(motherField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(dobField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(contactField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(searchPanel1Layout.createSequentialGroup()
                        .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(genderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(departmentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(nationalityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(designationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchPanel1Layout.createSequentialGroup()
                                .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(marriedCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(18, 18, 18)
                                .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(cityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(performanceField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(dojField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(dojlField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(stateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(aadhaarCardField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(updateRadio))
                            .addComponent(update))))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        searchDepartmentCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                searchDepartmentComboItemStateChanged(evt);
            }
        });

        searchDesignationCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                searchDesignationComboItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(usingEmployeeID))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(employeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(employeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(903, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(usingEmployeeName)
                        .addGap(75, 75, 75)
                        .addComponent(searchDepartmentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(searchDesignationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(283, 283, 283))))
            .addComponent(searchPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usingEmployeeID)
                    .addComponent(usingEmployeeName)
                    .addComponent(search)
                    .addComponent(searchDepartmentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchDesignationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(searchPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usingEmployeeIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_usingEmployeeIDItemStateChanged
        
        if( usingEmployeeID.isSelected() ) {
            employeeID.setEnabled(true);
            employeeID.setText(yourID);
        } else {
            employeeID.setText("");
            searchPanel1.setVisible(false);
            employeeID.setEnabled(false);
        }
        
    }//GEN-LAST:event_usingEmployeeIDItemStateChanged

    private void usingEmployeeNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_usingEmployeeNameItemStateChanged
        
        if( usingEmployeeName.isSelected() ) {
            employeeName.setText("");
            employeeName.setEnabled(true);
        } else {
            employeeName.setEnabled(false);
        }
        
    }//GEN-LAST:event_usingEmployeeNameItemStateChanged

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        
        if( usingEmployeeID.isSelected() ) {
            empID.setText("");
            try {
                if( employeeID.getText().equals("") )
                    throw new NullFieldException("EmployeeID nt Entered");
                
                query.setParameters("SearchEmployeeUsingEmployeeID", employeeID);
                query.getResult( empID,nameField,fatherField, motherField,
                                            genderField,nationalityField,dobField,
                                            contactField,marriedCombo,addressArea,
                                            cityCombo,stateCombo,aadhaarCardField,emailField,
                                            designationCombo,departmentCombo,qualificationArea,
                                            performanceField,dojField,dojlField,employeeImageLabel );
                
                int returnedValue = query.getReturnedValue();
                
                if( returnedValue == 1 ) {
                    searchPanel1.setVisible(true);
                    deptString = empID.getText().substring(0,3);
                    desigString = empID.getText().substring(4,7);
                    numberString = employeeID.getText().substring(8);
                    yourString = deptString + "-" + desigString + "-" + numberString;
                    empID.setText(yourString);
                    
                    if( dojlField.getDate() != null ) {
                        updateRadio.setEnabled(false);
                    } else {
                        updateRadio.setEnabled(true);
                    }
                    
                }else if( returnedValue == 0 ) {
                    JOptionPane.showMessageDialog(this, "Invalid EmployeeID");
                }
            } catch(NullFieldException e) {
                JOptionPane.showMessageDialog(this, "Enter EmployeeID");
            }
        } else if( usingEmployeeName.isSelected() ) {
            try {
                if( employeeName.getText().equals("") )
                    throw new NullFieldException("Employee Name not Entered");
                
                query.setParameters("SearchEmployeeUsingEmployeeName", employeeName);
                query.getReport(ReportBase.model);
                
                int returnedValue = query.getReturnedValue();
                
                if( returnedValue == 0 ) {
                    JOptionPane.showMessageDialog(this, "No Employee with Name : "+employeeName.getText());
                }
                
            } catch(NullFieldException e) {
                JOptionPane.showMessageDialog(this, "Enter Name");
            }
        } else {
            JOptionPane.showMessageDialog(this, "First Select Valid Option");
        }
        
    }//GEN-LAST:event_searchActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        
        try {
            ExceptionThrower.nullFields(nameField, fatherField, motherField, nationalityField,
                                            contactField, aadhaarCardField);
            
            ExceptionThrower.nullArea(addressArea, qualificationArea);
            ExceptionThrower.letterFound(false, contactField, aadhaarCardField);
            ExceptionThrower.requiredLength(MAX_LENGTH_CONTACT, contactField);
            ExceptionThrower.invalidDate(dobField);
            ExceptionThrower.ageCheck(dobField, "Date Of Birth", this);
            ExceptionThrower.requiredLength(MAX_LENGTH_AADHAAR, aadhaarCardField);
            
            int yourOption = JOptionPane.showConfirmDialog(this, "Are you Sure ?");
            if(yourOption == JOptionPane.YES_OPTION){
                
                query.setParameters("UpdatingEmployeeInfo", employeeID, empID, nameField,
                                            fatherField, motherField, genderField, nationalityField,
                                            dobField, contactField, marriedCombo, addressArea,
                                            cityCombo, stateCombo, emailField, designationCombo,
                                            departmentCombo, qualificationArea, performanceField,
                                            dojlField, selectedFilePath);

                query.getResult();
                
                //----returned value not required because always return 1 or 2 whick are successfull condition
                JOptionPane.showMessageDialog(this, "Saved Successfully!", "Done.", JOptionPane.NO_OPTION);
                searchPanel1.setVisible(false);
                employeeID.setText("");
                
                searchDepartmentCombo.setSelectedIndex(0);
                searchDesignationCombo.setSelectedIndex(0);
                updateRadio.setSelected(false);

                resetEnabled( false, nameField, fatherField, motherField, marriedCombo, genderField, dobField,
                                    dojlField, nationalityField, contactField, addressArea, cityCombo, stateCombo, designationCombo,
                                    departmentCombo, qualificationArea, performanceField, employeeImageLabel,
                                    emailField, update );
                resetEnabled( true, employeeID, usingEmployeeID, usingEmployeeName, search, 
                                    searchDepartmentCombo, searchDesignationCombo, employeeID );
                
            }
            
        } catch(NullFieldException e) {
            JOptionPane.showMessageDialog(this, "* fields must not be empty", "Empty * field", JOptionPane.INFORMATION_MESSAGE);
        } catch(LetterFoundException e) {
            JOptionPane.showMessageDialog(this, "** must contain only numbers", "Invalid ** fields", JOptionPane.INFORMATION_MESSAGE);
        } catch(RequiredLegthNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Contact No must be "+MAX_LENGTH_CONTACT+" characters long\nAadhaar Card No must be "+MAX_LENGTH_AADHAAR+" characters long", "Required Length Not Found", JOptionPane.INFORMATION_MESSAGE);
        } catch(TooYoungException e) {
            JOptionPane.showMessageDialog(this, "Too young to work", "Age Restrictions", JOptionPane.INFORMATION_MESSAGE);
        } catch(TooOldException e) {
            JOptionPane.showMessageDialog(this, "Too Old to work", "Age Restrictions", JOptionPane.INFORMATION_MESSAGE);
        } catch(InvalidDateFoundException e) {
            JOptionPane.showMessageDialog(this, "Select a Valid Date", "Invalid date ", JOptionPane.INFORMATION_MESSAGE);
        } catch(SymbolFoundException e) {
            JOptionPane.showMessageDialog(this, "Some Fields must contain conly alphabets", "Invalid Field Data", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_updateActionPerformed

    private void updateRadioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_updateRadioItemStateChanged
        
        if(updateRadio.isSelected()) {
            
            resetEnabled( true, nameField, fatherField, motherField, marriedCombo, genderField, dobField,
                    dojlField, nationalityField, contactField, addressArea, cityCombo, stateCombo,
                    designationCombo, departmentCombo, qualificationArea,performanceField, employeeImageLabel,
                    emailField, update );
            
            resetEnabled( false, usingEmployeeID,usingEmployeeName,search,searchDepartmentCombo,
                                searchDesignationCombo,employeeID );
            
        } else {
            resetEnabled( false, nameField, fatherField, motherField, marriedCombo, genderField, dobField,
                    dojlField, nationalityField, contactField, addressArea, cityCombo, stateCombo, designationCombo,
                    departmentCombo, qualificationArea, performanceField, employeeImageLabel,
                    emailField, update );
            
            resetEnabled( true, usingEmployeeID,usingEmployeeName,search,searchDepartmentCombo,
                                searchDesignationCombo,employeeID );
            
        }
    }//GEN-LAST:event_updateRadioItemStateChanged

    private void searchDepartmentComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_searchDepartmentComboItemStateChanged
        deptCode = searchDepartmentCombo.getSelectedItem().toString().substring(0, 3);
        yourID = deptCode + "-" + desigCode + "-";
        employeeID.setText(yourID);
        searchPanel1.setVisible(false);
    }//GEN-LAST:event_searchDepartmentComboItemStateChanged

    private void searchDesignationComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_searchDesignationComboItemStateChanged
        desigCode = searchDesignationCombo.getSelectedItem().toString().substring(0, 3);
        yourID = deptCode + "-" + desigCode + "-";
        employeeID.setText(yourID);
        searchPanel1.setVisible(false);
    }//GEN-LAST:event_searchDesignationComboItemStateChanged

    private void departmentComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_departmentComboItemStateChanged
        deptString = departmentCombo.getSelectedItem().toString().substring(0, 3);
        yourString = deptString + "-" + desigString + "-" + numberString;
        empID.setText(yourString);
    }//GEN-LAST:event_departmentComboItemStateChanged

    private void designationComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_designationComboItemStateChanged
        desigString = designationCombo.getSelectedItem().toString().substring(0, 3);
        yourString = deptString + "-" + desigString + "-" + numberString;
        empID.setText(yourString);
    }//GEN-LAST:event_designationComboItemStateChanged

    private void employeeImageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeImageLabelMouseClicked
        if( updateRadio.isSelected() )
        selectedFilePath = new YourImage().setImage(employeeImageLabel, false);
    }//GEN-LAST:event_employeeImageLabelMouseClicked

    private void employeeIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_employeeIDKeyTyped
        searchPanel1.setVisible(false);
    }//GEN-LAST:event_employeeIDKeyTyped
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchAndUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchAndUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchAndUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchAndUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchAndUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aadhaarCardField;
    private javax.swing.JTextArea addressArea;
    private javax.swing.JComboBox<String> cityCombo;
    private javax.swing.JTextField contactField;
    private javax.swing.JComboBox<String> departmentCombo;
    private javax.swing.JComboBox<String> designationCombo;
    private com.toedter.calendar.JDateChooser dobField;
    private com.toedter.calendar.JDateChooser dojField;
    private com.toedter.calendar.JDateChooser dojlField;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField empID;
    private javax.swing.JTextField employeeID;
    private javax.swing.JLabel employeeImageLabel;
    private javax.swing.JTextField employeeName;
    private javax.swing.JTextField fatherField;
    private javax.swing.JTextField genderField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> marriedCombo;
    private javax.swing.JTextField motherField;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField nationalityField;
    private javax.swing.JTextField performanceField;
    private javax.swing.JTextArea qualificationArea;
    private javax.swing.JButton search;
    private javax.swing.JComboBox<String> searchDepartmentCombo;
    private javax.swing.JComboBox<String> searchDesignationCombo;
    private javax.swing.JPanel searchPanel1;
    private javax.swing.JComboBox<String> stateCombo;
    private javax.swing.JButton update;
    private javax.swing.JRadioButton updateRadio;
    private javax.swing.JRadioButton usingEmployeeID;
    private javax.swing.JRadioButton usingEmployeeName;
    private javax.swing.ButtonGroup yourChoice;
    // End of variables declaration//GEN-END:variables
}
