/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package settings;

import Employee.NewEmployee;
import Employee.SearchAndUpdate;
import databaseConnections.QueryExecution;
import employeemanagementsystem.LoginPage;
import employeemanagementsystem.WelcomeToEMS;
import images.YourImage;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import master.DepartmentMaster;
import master.SalaryScaleMaster;
import reports.AdvanceReport;
import reports.AttendanceReport;
import reports.EmployeesReport;
import reports.PaymentReport;
import transactions.Advance;
import transactions.Attendance;
import transactions.MonthlyPayments;

/**
 *
 * @author ask
 */
public class UserSettings extends javax.swing.JFrame {

    /**
     * Creates new form UserSettings
     */
    private final QueryExecution query;
    private File selectedFilePath;
    public static WelcomeToEMS wtems;
    public static NewEmployee newEmployee;
    public static SearchAndUpdate searchAndUpdate;
    public static DepartmentMaster departmentMaster;
    public static SalaryScaleMaster salaryScaleMaster;
    public static MonthlyPayments payments;
    public static Attendance attendance;
    public static Advance adv;
    public static EmployeesReport employeesReport;
    public static AttendanceReport attendanceReport;
    public static PaymentReport paymentReport;
    public static AdvanceReport advanceReport;
    
    
    public UserSettings() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        nameField.setEnabled(false);
        
        query = new QueryExecution();
        query.setParameters("UserSettingPage", null);
        query.getResult(nameField,imageLabel);
        
        int returnedValue = query.getReturnedValue();
        if( returnedValue == 0 ) {
            new YourImage().setImage(imageLabel, true);
        }
        changePanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backupDialog = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        backupLocation = new javax.swing.JTextField();
        chooseLocation = new javax.swing.JButton();
        doBackup = new javax.swing.JButton();
        restoreDialog = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        savedFileLocation = new javax.swing.JTextField();
        bakFileLocation = new javax.swing.JButton();
        doRestore = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        changePassword = new javax.swing.JLabel();
        changeUsername = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        changePanel = new javax.swing.JLayeredPane();
        passwordPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        oldField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        newField = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        confirmField = new javax.swing.JPasswordField();
        changeYourPassword = new javax.swing.JButton();
        namePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        newNameField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        changeYourUsername = new javax.swing.JButton();
        backup = new javax.swing.JLabel();
        restore = new javax.swing.JLabel();

        backupDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        backupDialog.setTitle("Backup");
        backupDialog.setAlwaysOnTop(true);
        backupDialog.setModal(true);

        jLabel7.setText("Backup to : ");

        chooseLocation.setText("Choose Location");
        chooseLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseLocationActionPerformed(evt);
            }
        });

        doBackup.setText("Backup");
        doBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doBackupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backupDialogLayout = new javax.swing.GroupLayout(backupDialog.getContentPane());
        backupDialog.getContentPane().setLayout(backupDialogLayout);
        backupDialogLayout.setHorizontalGroup(
            backupDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backupDialogLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(backupDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doBackup)
                    .addGroup(backupDialogLayout.createSequentialGroup()
                        .addComponent(backupLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chooseLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        backupDialogLayout.setVerticalGroup(
            backupDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backupDialogLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(backupDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(backupLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseLocation))
                .addGap(18, 18, 18)
                .addComponent(doBackup)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        restoreDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        restoreDialog.setTitle("Restore");
        restoreDialog.setModal(true);

        jLabel9.setText("Restore From");

        bakFileLocation.setText("Choose Location");
        bakFileLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bakFileLocationActionPerformed(evt);
            }
        });

        doRestore.setText("Restore");
        doRestore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doRestoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout restoreDialogLayout = new javax.swing.GroupLayout(restoreDialog.getContentPane());
        restoreDialog.getContentPane().setLayout(restoreDialogLayout);
        restoreDialogLayout.setHorizontalGroup(
            restoreDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restoreDialogLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(restoreDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doRestore)
                    .addGroup(restoreDialogLayout.createSequentialGroup()
                        .addComponent(savedFileLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bakFileLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        restoreDialogLayout.setVerticalGroup(
            restoreDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restoreDialogLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(restoreDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(savedFileLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bakFileLocation))
                .addGap(18, 18, 18)
                .addComponent(doRestore)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Settings");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setText("Settings");

        changePassword.setText("Change Password");
        changePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changePasswordMouseClicked(evt);
            }
        });

        changeUsername.setText("Change Username");
        changeUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeUsernameMouseClicked(evt);
            }
        });

        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        imageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageLabelMouseClicked(evt);
            }
        });

        nameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setText("Old Password");

        jLabel3.setText("New Password");

        jLabel4.setText("Confirm Password");

        changeYourPassword.setText("Change");
        changeYourPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeYourPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout passwordPanelLayout = new javax.swing.GroupLayout(passwordPanel);
        passwordPanel.setLayout(passwordPanelLayout);
        passwordPanelLayout.setHorizontalGroup(
            passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(76, 76, 76)
                .addGroup(passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(passwordPanelLayout.createSequentialGroup()
                        .addComponent(changeYourPassword)
                        .addGap(0, 129, Short.MAX_VALUE))
                    .addComponent(oldField)
                    .addComponent(newField)
                    .addComponent(confirmField))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        passwordPanelLayout.setVerticalGroup(
            passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(oldField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(newField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(confirmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(changeYourPassword)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel5.setText("New Username");

        jLabel6.setText("Password");

        changeYourUsername.setText("Change");
        changeYourUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeYourUsernameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout namePanelLayout = new javax.swing.GroupLayout(namePanel);
        namePanel.setLayout(namePanelLayout);
        namePanelLayout.setHorizontalGroup(
            namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(74, 74, 74)
                .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changeYourUsername)
                    .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(newNameField)
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        namePanelLayout.setVerticalGroup(
            namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(newNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(changeYourUsername)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        changePanel.setLayer(passwordPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        changePanel.setLayer(namePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout changePanelLayout = new javax.swing.GroupLayout(changePanel);
        changePanel.setLayout(changePanelLayout);
        changePanelLayout.setHorizontalGroup(
            changePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(changePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(namePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        changePanelLayout.setVerticalGroup(
            changePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(passwordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        backup.setText("Backup");
        backup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backupMouseClicked(evt);
            }
        });

        restore.setText("Restore");
        restore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restoreMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(changePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(changePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(changeUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(backup, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(128, 128, 128)
                            .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(restore)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(605, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {backup, changePassword, changeUsername, jLabel1, logout, restore});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {imageLabel, nameField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(changePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(changeUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(backup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restore))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(changePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {backup, changePassword, changeUsername, jLabel1, logout, restore});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabelMouseClicked
        
        selectedFilePath = new YourImage().setImage(imageLabel, false);
        if(selectedFilePath != null) {
            query.setParameters("SettingLoginImage", selectedFilePath);
            query.getResult(imageLabel);
        }
    }//GEN-LAST:event_imageLabelMouseClicked

    private void changeYourPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeYourPasswordActionPerformed
        
        if(oldField.getPassword().toString().equals("")) {
            JOptionPane.showMessageDialog(this, "Old Password Field Must Not be Empty");
        } else if(newField.getPassword().toString().equals("")) {
            JOptionPane.showMessageDialog(this, "New Password Field Must Not be Empty");
        } /*else if(!confirmField.getPassword().toString().equals(newField.getPassword().toString())){
            JOptionPane.showMessageDialog(this, "Password Didn't Matched");
        }*/ else {
            query.setParameters("ChangePassword", nameField,oldField,newField);
            query.getResult();
            int returnedValue = query.getReturnedValue();
            if(returnedValue == 1) {
                JOptionPane.showMessageDialog(this, "Changed Successfull");
                passwordPanel.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Wrong Old Password");
            }
        }
    }//GEN-LAST:event_changeYourPasswordActionPerformed

    private void changeYourUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeYourUsernameActionPerformed
        if(newNameField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "New Username Field Must Not be Empty");
        } else if(passwordField.getPassword().toString().equals("")) {
            JOptionPane.showMessageDialog(this, "Password Field Must not be empty");
        } else {
            query.setParameters("ChangeUsername", newNameField,nameField,passwordField);
            query.getResult();
            int returnedValue = query.getReturnedValue();
            if(returnedValue == 1){
                JOptionPane.showMessageDialog(this, "Changed Successfull");
                nameField.setText(newNameField.getText());
                namePanel.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Worng Password entered");
            }
        }
    }//GEN-LAST:event_changeYourUsernameActionPerformed

    private void changePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswordMouseClicked
        changePanel.setVisible(true);
        namePanel.setVisible(false);
        passwordPanel.setVisible(true);
        oldField.setText("");
        newField.setText("");
        confirmField.setText("");
    }//GEN-LAST:event_changePasswordMouseClicked

    private void changeUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeUsernameMouseClicked
        changePanel.setVisible(true);
        passwordPanel.setVisible(false);
        namePanel.setVisible(true);
        newNameField.setText("");
        passwordField.setText("");
    }//GEN-LAST:event_changeUsernameMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        changePanel.setVisible(false);
    }//GEN-LAST:event_formMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        int yourOption = JOptionPane.showConfirmDialog(this, "Sure to Logout", "Logout", JOptionPane.YES_NO_OPTION);
        if(yourOption == JOptionPane.YES_OPTION) {
            if(wtems != null) {
                wtems.dispose();
            }
            if(newEmployee != null) {
                newEmployee.dispose();
            }
            if(searchAndUpdate != null) {
                searchAndUpdate.dispose();
            }
            if(departmentMaster != null) {
                departmentMaster.dispose();
            }
            if(salaryScaleMaster != null) {
                salaryScaleMaster.dispose();
            }
            if(payments != null) {
                payments.dispose();
            }
            if(attendance != null) {
                attendance.dispose();
            }
            if(adv != null) {
                adv.dispose();
            }
            if(employeesReport != null) {
                employeesReport.dispose();
            }
            if(attendanceReport != null) {
                attendanceReport.dispose();
            }
            if(paymentReport != null) {
                paymentReport.dispose();
            }
            if(advanceReport != null) {
                advanceReport.dispose();
            }
            new LoginPage().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_logoutMouseClicked

    private void chooseLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseLocationActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        chooser.showOpenDialog(backupDialog);
        String path = chooser.getSelectedFile().toString();
        path = path+"\\EMS.bak";
        backupLocation.setText(path);
    }//GEN-LAST:event_chooseLocationActionPerformed

    private void backupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backupMouseClicked
        backupDialog.setSize(700, 300);
        backupLocation.setEditable(false);
        backupDialog.setVisible(true);
    }//GEN-LAST:event_backupMouseClicked

    private void doBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doBackupActionPerformed
        
        query.setParameters("BackupData", backupLocation);
        query.getResult(null);
        int retVal = query.getReturnedValue();
        if( retVal == 1 ) {
            JOptionPane.showMessageDialog(backupDialog, "Backup Done.");
            backupLocation.setText("");
            backupDialog.dispose();
        } else {
            JOptionPane.showMessageDialog(backupDialog, "Backup Failed.");
        }
    }//GEN-LAST:event_doBackupActionPerformed

    private void bakFileLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bakFileLocationActionPerformed
        
        JFileChooser choosePhoto = new JFileChooser();
        FileNameExtensionFilter fileExtentions = new FileNameExtensionFilter("Back File", "bak");
        choosePhoto.setFileFilter(fileExtentions);
        choosePhoto.showOpenDialog(restoreDialog);
        String str = choosePhoto.getSelectedFile().getAbsolutePath();
        savedFileLocation.setText(str);
        
    }//GEN-LAST:event_bakFileLocationActionPerformed

    private void doRestoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doRestoreActionPerformed
        query.setParameters("RestoreData", bakFileLocation);
        query.getResult(null);
        int retVal = query.getReturnedValue();
        if(retVal == 1 ) {
            JOptionPane.showMessageDialog(restoreDialog, "Restore Done.");
            bakFileLocation.setText("");
            restoreDialog.dispose();
        } else {
            JOptionPane.showMessageDialog(restoreDialog, "Restore Failed.");
        }
    }//GEN-LAST:event_doRestoreActionPerformed

    private void restoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restoreMouseClicked
        restoreDialog.setSize(700, 300);
        savedFileLocation.setEditable(false);
        restoreDialog.setVisible(true);
    }//GEN-LAST:event_restoreMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserSettings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backup;
    private javax.swing.JDialog backupDialog;
    private javax.swing.JTextField backupLocation;
    private javax.swing.JButton bakFileLocation;
    private javax.swing.JLayeredPane changePanel;
    private javax.swing.JLabel changePassword;
    private javax.swing.JLabel changeUsername;
    private javax.swing.JButton changeYourPassword;
    private javax.swing.JButton changeYourUsername;
    private javax.swing.JButton chooseLocation;
    private javax.swing.JPasswordField confirmField;
    private javax.swing.JButton doBackup;
    private javax.swing.JButton doRestore;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel logout;
    private javax.swing.JTextField nameField;
    private javax.swing.JPanel namePanel;
    private javax.swing.JPasswordField newField;
    private javax.swing.JTextField newNameField;
    private javax.swing.JPasswordField oldField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JPanel passwordPanel;
    private javax.swing.JLabel restore;
    private javax.swing.JDialog restoreDialog;
    private javax.swing.JTextField savedFileLocation;
    // End of variables declaration//GEN-END:variables
}
