
package employeemanagementsystem;

import transactions.Attendance;
import Employee.NewEmployee;
import Employee.SearchAndUpdate;
import images.BackgroundImage;
import java.awt.Frame;
import master.DepartmentMaster;
import master.SalaryScaleMaster;
import javax.swing.JOptionPane;
import static utilities.Utilities.turnVisible;
import static utilities.Utilities.resetOpaque;
import reports.AdvanceReport;
import reports.AttendanceReport;
import reports.EmployeesReport;
import reports.PaymentReport;
import settings.UserSettings;
import static settings.UserSettings.adv;
import static settings.UserSettings.advanceReport;
import static settings.UserSettings.attendance;
import static settings.UserSettings.attendanceReport;
import static settings.UserSettings.departmentMaster;
import static settings.UserSettings.employeesReport;
import static settings.UserSettings.newEmployee;
import static settings.UserSettings.paymentReport;
import static settings.UserSettings.payments;
import static settings.UserSettings.salaryScaleMaster;
import static settings.UserSettings.searchAndUpdate;
import transactions.Advance;
import transactions.MonthlyPayments;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ask
 */

public class WelcomeToEMS extends javax.swing.JFrame {

    /**
     * Creates new form WelcomeToEMS
     */
    
    private UserSettings userSettings;
    
    public WelcomeToEMS() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        
        turnVisible(false, masterPanel,employeePanel,transactionsPanel,reportsPanel);
        resetOpaque(masterPanel,employeePanel,transactionsPanel,reportsPanel);
        
        BackgroundImage.setBackgroundImage(this,"/Background1.jpg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        master = new javax.swing.JButton();
        employee = new javax.swing.JButton();
        transactions = new javax.swing.JButton();
        reports = new javax.swing.JButton();
        settings = new javax.swing.JButton();
        logOut = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        reportsPanel = new javax.swing.JPanel();
        employeeReport = new javax.swing.JButton();
        attendenceReports = new javax.swing.JButton();
        paymentReports = new javax.swing.JButton();
        advanceReports = new javax.swing.JButton();
        transactionsPanel = new javax.swing.JPanel();
        monthlyPayments = new javax.swing.JButton();
        attendence = new javax.swing.JButton();
        advance = new javax.swing.JButton();
        employeePanel = new javax.swing.JPanel();
        employeeSearchAndUpdate = new javax.swing.JButton();
        newEmployeeButton = new javax.swing.JButton();
        masterPanel = new javax.swing.JPanel();
        department = new javax.swing.JButton();
        salaryScale = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome TO EMS");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        master.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        master.setText("Master");
        master.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterActionPerformed(evt);
            }
        });

        employee.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        employee.setText("Employee");
        employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeActionPerformed(evt);
            }
        });

        transactions.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        transactions.setText("Transactions");
        transactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionsActionPerformed(evt);
            }
        });

        reports.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reports.setText("Reports");
        reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsActionPerformed(evt);
            }
        });

        settings.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        settings.setText("Settings");
        settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsActionPerformed(evt);
            }
        });

        logOut.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logOut.setText("Logout");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        employeeReport.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        employeeReport.setText("Employee Reports");
        employeeReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeReportActionPerformed(evt);
            }
        });

        attendenceReports.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        attendenceReports.setText("Attendence Reports");
        attendenceReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendenceReportsActionPerformed(evt);
            }
        });

        paymentReports.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        paymentReports.setText("Payment Reports");
        paymentReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentReportsActionPerformed(evt);
            }
        });

        advanceReports.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        advanceReports.setText("Advance Reports");
        advanceReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advanceReportsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reportsPanelLayout = new javax.swing.GroupLayout(reportsPanel);
        reportsPanel.setLayout(reportsPanelLayout);
        reportsPanelLayout.setHorizontalGroup(
            reportsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportsPanelLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(reportsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(advanceReports, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentReports, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attendenceReports, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeReport, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        reportsPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {advanceReports, attendenceReports, employeeReport, paymentReports});

        reportsPanelLayout.setVerticalGroup(
            reportsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportsPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(employeeReport, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(attendenceReports, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(paymentReports, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(advanceReports, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        reportsPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {advanceReports, attendenceReports, employeeReport, paymentReports});

        monthlyPayments.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        monthlyPayments.setText("Monthly Payments");
        monthlyPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthlyPaymentsActionPerformed(evt);
            }
        });

        attendence.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        attendence.setText("Attenence");
        attendence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendenceActionPerformed(evt);
            }
        });

        advance.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        advance.setText("Advance");
        advance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout transactionsPanelLayout = new javax.swing.GroupLayout(transactionsPanel);
        transactionsPanel.setLayout(transactionsPanelLayout);
        transactionsPanelLayout.setHorizontalGroup(
            transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionsPanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(monthlyPayments, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(attendence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(advance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        transactionsPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {advance, attendence, monthlyPayments});

        transactionsPanelLayout.setVerticalGroup(
            transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionsPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(monthlyPayments, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(attendence, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(advance, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        transactionsPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {advance, attendence, monthlyPayments});

        employeeSearchAndUpdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        employeeSearchAndUpdate.setText("Search/Update");
        employeeSearchAndUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeSearchAndUpdateActionPerformed(evt);
            }
        });

        newEmployeeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newEmployeeButton.setText("New Employee");
        newEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEmployeeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout employeePanelLayout = new javax.swing.GroupLayout(employeePanel);
        employeePanel.setLayout(employeePanelLayout);
        employeePanelLayout.setHorizontalGroup(
            employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePanelLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(newEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeSearchAndUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        employeePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {employeeSearchAndUpdate, newEmployeeButton});

        employeePanelLayout.setVerticalGroup(
            employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(newEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(employeeSearchAndUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        employeePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {employeeSearchAndUpdate, newEmployeeButton});

        department.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        department.setText("Department");
        department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentActionPerformed(evt);
            }
        });

        salaryScale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        salaryScale.setText("SalaryScale");
        salaryScale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryScaleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout masterPanelLayout = new javax.swing.GroupLayout(masterPanel);
        masterPanel.setLayout(masterPanelLayout);
        masterPanelLayout.setHorizontalGroup(
            masterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masterPanelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(masterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salaryScale, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        masterPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {department, salaryScale});

        masterPanelLayout.setVerticalGroup(
            masterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masterPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(salaryScale, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        masterPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {department, salaryScale});

        jLayeredPane1.setLayer(reportsPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(transactionsPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(employeePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(masterPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(reportsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(transactionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(employeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(masterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(reportsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 11, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(transactionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(employeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(masterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(master, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(employee, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(transactions, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reports, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(settings, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(982, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(master, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employee, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reports, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transactions, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settings, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(465, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void masterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterActionPerformed
        masterPanel.setVisible(true);
        turnVisible(false, employeePanel,transactionsPanel,reportsPanel);
    }//GEN-LAST:event_masterActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        int yourOption = JOptionPane.showConfirmDialog(this, "Sure to Logout", "Logout", JOptionPane.YES_NO_OPTION);
        if(yourOption == JOptionPane.YES_OPTION) {
            
            if(newEmployee != null) {
                newEmployee.dispose();
            }
            if(searchAndUpdate != null) {
                searchAndUpdate.dispose();
            }
            if(departmentMaster != null) {
                departmentMaster.dispose();
            }
            if(salaryScaleMaster != null) {
                salaryScaleMaster.dispose();
            }
            if(payments != null) {
                payments.dispose();
            }
            if(attendance != null) {
                attendance.dispose();
            }
            if(adv != null) {
                adv.dispose();
            }
            if(employeesReport != null) {
                employeesReport.dispose();
            }
            if(attendanceReport != null) {
                attendanceReport.dispose();
            }
            if(paymentReport != null) {
                paymentReport.dispose();
            }
            if(advanceReport != null) {
                advanceReport.dispose();
            }
            
            new LoginPage().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_logOutActionPerformed

    private void settingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsActionPerformed
        if(userSettings == null) {
            userSettings = new UserSettings();
        }
        userSettings.setVisible(true);
    }//GEN-LAST:event_settingsActionPerformed

    private void employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeActionPerformed
        employeePanel.setVisible(true);
        turnVisible(false, transactionsPanel,reportsPanel,masterPanel);
    }//GEN-LAST:event_employeeActionPerformed

    private void transactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionsActionPerformed
        transactionsPanel.setVisible(true);
        turnVisible(false, employeePanel,reportsPanel,masterPanel);
    }//GEN-LAST:event_transactionsActionPerformed

    private void departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentActionPerformed
        
        String passwordToEnter = JOptionPane.showInputDialog(this, "Enter Password to Enter", "Password", JOptionPane.QUESTION_MESSAGE);
        if(!passwordToEnter.equals("")) {
            if(passwordToEnter.equals("Anand")) {
                if(UserSettings.departmentMaster == null) {
                    UserSettings.departmentMaster = new DepartmentMaster();
                } else {
                    departmentMaster.setState(Frame.NORMAL);
                }
                UserSettings.departmentMaster.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Wrong Password");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Password Not Entered");
        }
        
    }//GEN-LAST:event_departmentActionPerformed

    private void newEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEmployeeButtonActionPerformed
        if(UserSettings.newEmployee == null) {
            UserSettings.newEmployee = new NewEmployee();
        }else if(!newEmployee.isDisplayable()){
                UserSettings.newEmployee = new NewEmployee();
        } else {
            newEmployee.setState(Frame.NORMAL);
        }
        UserSettings.newEmployee.setVisible(true);
    }//GEN-LAST:event_newEmployeeButtonActionPerformed

    private void employeeSearchAndUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeSearchAndUpdateActionPerformed
        if(UserSettings.searchAndUpdate == null) {
            UserSettings.searchAndUpdate = new SearchAndUpdate();
        } else if(!searchAndUpdate.isDisplayable()){
                UserSettings.searchAndUpdate = new SearchAndUpdate();
        } else {
            searchAndUpdate.setState(Frame.NORMAL);
        }
        UserSettings.searchAndUpdate.setVisible(true);
    }//GEN-LAST:event_employeeSearchAndUpdateActionPerformed

    private void salaryScaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryScaleActionPerformed
        String passwordToEnter = JOptionPane.showInputDialog(this, "Enter Password to Enter");
        if( !passwordToEnter.equals("") ) {
            if( passwordToEnter.equals("Anand") ) {
                if(UserSettings.salaryScaleMaster == null) {
                    UserSettings.salaryScaleMaster = new SalaryScaleMaster();
                } else if(!salaryScaleMaster.isDisplayable()){
                    UserSettings.salaryScaleMaster = new SalaryScaleMaster();
                } else {
                    salaryScaleMaster.setState(Frame.NORMAL);
                }
                UserSettings.salaryScaleMaster.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Wrong Password");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Password Not Entered");
        }
    }//GEN-LAST:event_salaryScaleActionPerformed

    private void reportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsActionPerformed
        reportsPanel.setVisible(true);
        turnVisible(false, employeePanel,transactionsPanel,masterPanel);
    }//GEN-LAST:event_reportsActionPerformed

    private void attendenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendenceActionPerformed
        if(UserSettings.attendance == null) {
            UserSettings.attendance = new Attendance();
        } else if(!attendance.isDisplayable()){
            UserSettings.attendance = new Attendance();
        } else {
            attendance.setState(Frame.NORMAL);
        }
        UserSettings.attendance.setVisible(true);
    }//GEN-LAST:event_attendenceActionPerformed

    private void employeeReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeReportActionPerformed
        if(UserSettings.employeesReport == null) {
            UserSettings.employeesReport = new EmployeesReport();
        } else if(!employeesReport.isDisplayable()){
            UserSettings.employeesReport = new EmployeesReport();
        } else {
            employeesReport.setState(Frame.NORMAL);
        }
        UserSettings.employeesReport.setVisible(true);
    }//GEN-LAST:event_employeeReportActionPerformed

    private void monthlyPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthlyPaymentsActionPerformed
        if(UserSettings.payments == null) {
            UserSettings.payments = new MonthlyPayments();
        } else if(!payments.isDisplayable()){
            UserSettings.payments = new MonthlyPayments();
        } else {
            payments.setState(Frame.NORMAL);
        }
        UserSettings.payments.setVisible(true);
    }//GEN-LAST:event_monthlyPaymentsActionPerformed

    private void advanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advanceActionPerformed
        if(UserSettings.adv == null) {
            UserSettings.adv = new Advance();
        } else if(!adv.isDisplayable()){
            UserSettings.adv = new Advance();
        } else {
            adv.setState(Frame.NORMAL);
        }
        UserSettings.adv.setVisible(true);
    }//GEN-LAST:event_advanceActionPerformed

    private void attendenceReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendenceReportsActionPerformed
        if(UserSettings.attendanceReport == null) {
            UserSettings.attendanceReport = new AttendanceReport();
        } else if(!attendanceReport.isDisplayable()){
            UserSettings.attendanceReport = new AttendanceReport();
        } else {
            attendanceReport.setState(Frame.NORMAL);
        }
        UserSettings.attendanceReport.setVisible(true);
    }//GEN-LAST:event_attendenceReportsActionPerformed

    private void paymentReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentReportsActionPerformed
        if(UserSettings.paymentReport == null){
            UserSettings.paymentReport = new PaymentReport();
        } else if(!paymentReport.isDisplayable()){
            UserSettings.paymentReport = new PaymentReport();
        } else {
            paymentReport.setState(Frame.NORMAL);
        }
        UserSettings.paymentReport.setVisible(true);
    }//GEN-LAST:event_paymentReportsActionPerformed

    private void advanceReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advanceReportsActionPerformed
        if(UserSettings.advanceReport == null) {
            UserSettings.advanceReport = new AdvanceReport();
        } else if(!advanceReport.isDisplayable()){
            UserSettings.advanceReport = new AdvanceReport();
        } else {
            advanceReport.setState(Frame.NORMAL);
        }
        UserSettings.advanceReport.setVisible(true);
    }//GEN-LAST:event_advanceReportsActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        masterPanel.setVisible(false);
        employeePanel.setVisible(false);
        transactionsPanel.setVisible(false);
        reportsPanel.setVisible(false);
    }//GEN-LAST:event_formMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeToEMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeToEMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeToEMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeToEMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeToEMS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton advance;
    private javax.swing.JButton advanceReports;
    private javax.swing.JButton attendence;
    private javax.swing.JButton attendenceReports;
    private javax.swing.JButton department;
    private javax.swing.JButton employee;
    private javax.swing.JPanel employeePanel;
    private javax.swing.JButton employeeReport;
    private javax.swing.JButton employeeSearchAndUpdate;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton logOut;
    private javax.swing.JButton master;
    private javax.swing.JPanel masterPanel;
    private javax.swing.JButton monthlyPayments;
    private javax.swing.JButton newEmployeeButton;
    private javax.swing.JButton paymentReports;
    private javax.swing.JButton reports;
    private javax.swing.JPanel reportsPanel;
    private javax.swing.JButton salaryScale;
    private javax.swing.JButton settings;
    private javax.swing.JButton transactions;
    private javax.swing.JPanel transactionsPanel;
    // End of variables declaration//GEN-END:variables
}
